"""empty message

Revision ID: 61e561ed5677
Revises: 
Create Date: 2021-04-27 23:27:35.172358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e561ed5677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('depended_algorithms', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('questions', 'algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'questions', 'algorithms', ['algorithm_id'], ['id'])
    op.alter_column('results', 'algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('results', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'results', 'algorithms', ['algorithm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.alter_column('results', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('results', 'algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('algorithms', 'depended_algorithms')
    # ### end Alembic commands ###
