"""empty message

Revision ID: df7bd95e9374
Revises: 61e561ed5677
Create Date: 2021-04-27 23:44:57.364336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7bd95e9374'
down_revision = '61e561ed5677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('depends', sa.Boolean(), nullable=True))
    op.drop_index('algorithms_id_uindex', table_name='algorithms')
    op.drop_column('algorithms', 'is_used')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('algorithms_id_uindex', 'algorithms', ['id'], unique=True)
    op.drop_column('algorithms', 'depends')
    # ### end Alembic commands ###
